version: '2'
services:
  mongodb:
    image: mongo
    network_mode: host
    volumes:
      - ./db-data:/data/db
    command: "/bin/bash -c \"mongod\""
  webapp:
    image: node
    ports:
      - "3000:3000"
    network_mode: host
    volumes:
      - ./Webapp:/usr/src/app
    command: "/bin/bash -c \"cd /usr/src/app && npm install -g yo gulp-cli && gulp serve\""
